---
- name: debuging vars
  debug:
    var: security_group

- name: debuging pub var
  debug:
    var: pub_subnet

- name: start creating ec2 machine
  amazon.aws.ec2_instance:
    name: "ec2_ansible"
    instance_type: "t2.micro"
    image_id: "ami-003d3d03cfe1b0468"
    key_name: "ansible-key"
    subnet_id: "{{ pub_subnet.subnet.id }}"
    security_group: "{{ security_group.group_id }}"
    state: present
    region: "{{loc}}"
    tags:
       "ENV" : "TEST"
  register: ec2