---
- name: started creating security group
  amazon.aws.ec2_security_group:
    name: "security-group-public"
    description: "security grp"
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    region: "{{ loc }}"
    rules:
    # Ingress (Inbound) Rules
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"  # Allow SSH from anywhere
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "0.0.0.0/0"  # Allow HTTP from anywhere
    # Egress (Outbound) Rules
      - proto: all
        from_port: -1
        to_port: -1
        cidr_ip: "0.0.0.0/0"
  register: security_group

- name: set fact for security group
  set_fact:
    security_group: "{{security_group}}"
