---
- name: Started VPC creation
  amazon.aws.ec2_vpc_net:
    cidr_block: "{{ cidr }}"
    name: "vpc-through-code"
    state: present
    region: "{{ loc }}"
  register: vpc_reg
- name: set a fact
  set_fact:
    vpc: "{{vpc_reg}}"
